CREATE TABLE outagetable (
    createdon VARCHAR(255),
    network_level VARCHAR(255),
    outage_status VARCHAR(255),
    ibc VARCHAR(255),
    outage_type VARCHAR(255),
    outage_id VARCHAR(255),
    outage_subtype VARCHAR(255),
    fdr_id VARCHAR(255),
    fdr_name VARCHAR(255),
    TAT VARCHAR(255),
    cluster VARCHAR(255),
    punch_close_at VARCHAR(255),
    punching_delay VARCHAR(255),
    punch_create_at VARCHAR(255),
    is_rain_tripping VARCHAR(255),
    cluster_id INT,
    last_updated_on VARCHAR(255),
    loss_category VARCHAR(255),
    duration VARCHAR(255),
    initial_off_reason VARCHAR(255),
    dts_id VARCHAR(255),
    dts_name VARCHAR(255),
    closing_remarks VARCHAR(255),
    grid_name VARCHAR(255),
);
